- name: Configure BGP on Arista switches
  hosts: arista_switches
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Configure BGP on switch1
      arista.eos.eos_bgp_global:
        asn: 65001
        router_id: 1.1.1.1
        log_neighbor_changes: true
        neighbors:
          - ip: 192.168.12.2
            remote_as: 65002
            update_source: Loopback0
        networks:
          - ip_prefix: 192.168.13.0/24
            route_map: null
            mask_length_range: null
      register: bgp_config_switch1

    - name: Configure BGP on switch2
      arista.eos.eos_bgp_global:
        asn: 65002
        router_id: 2.2.2.2
        log_neighbor_changes: true
        neighbors:
          - ip: 192.168.12.1
            remote_as: 65001
            update_source: Loopback0
        networks:
          - ip_prefix: 192.168.12.0/24
            route_map: null
            mask_length_range: null
      register: bgp_config_switch2

    - name: Configure BGP on switch3
      arista.eos.eos_bgp_global:
        asn: 65003
        router_id: 3.3.3.3
        log_neighbor_changes: true
        neighbors:
          - ip: 192.168.23.2
            remote_as: 65004
            update_source: Loopback0
        networks:
          - ip_prefix: 192.168.33.0/24
            route_map: null
            mask_length_range: null
      register: bgp_config_switch3

    - name: Configure BGP on switch4
      arista.eos.eos_bgp_global:
        asn: 65004
        router_id: 4.4.4.4
        log_neighbor_changes: true
        neighbors:
          - ip: 192.168.23.1
            remote_as: 65003
            update_source: Loopback0
        networks:
          - ip_prefix: 192.168.23.0/24
            route_map: null
            mask_length_range: null
      register: bgp_config_switch4

    - name: Configure BGP on switch5
      arista.eos.eos_bgp_global:
        asn: 65005
        router_id: 5.5.5.5
        log_neighbor_changes: true
        neighbors:
          - ip: 192.168.34.2
            remote_as: 65006
            update_source: Loopback0
        networks:
          - ip_prefix: 192.168.35.0/24
            route_map: null
            mask_length_range: null
      register: bgp_config_switch5
