#ansible-playbook -i hosts.yml lab_setup.yml
- hosts: 10.32.251.246
  gather_facts: no
  vars:
    gns3_url: "http://10.32.251.246:80"
    gns3_nodes_spec:
      - name: "iosvl2-01"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl3-01"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl2-02"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl3-02"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl2-03"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl3-03"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl2-04"
        template: "Arista vEOS 4.29.1F"
      - name: "iosvl3-04"
        template: "Arista vEOS 4.29.1F"

    gns3_links_spec:
      - ["iosvl2-01", "eth1", "iosvl3-01", "eth1"]
      - ["iosvl3-01", "eth2", "iosvl2-02", "eth2"]
      - ["iosvl2-02", "eth3", "iosvl3-02", "eth3"]
      - ["iosvl3-02", "eth4", "iosvl2-03", "eth4"]
      - ["iosvl2-03", "eth5", "iosvl3-03", "eth5"]
      - ["iosvl3-03", "eth6", "iosvl2-04", "eth6"]
      - ["iosvl2-04", "eth7", "iosvl3-04", "eth7"]


  collections:
    - davidban77.gns3
  tasks:
    - name: "Create network topology"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "BGP-Config"
        state: present
        nodes_spec: "{{ gns3_nodes_spec }}"
        links_spec: "{{ gns3_links_spec }}"

    - name: "Start nodes"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "BGP-Config"
        state: opened
        nodes_state: started
        nodes_strategy: one_by_one


    - name: "Configure BGP on iosvl3-01"
      ios_command:
        provider:
          host: "{{ gns3_url }}"
          username: "cisco"
          password: "cisco"
          authorize: yes
          auth_pass: "cisco"
        commands:
        - "router bgp 65001"
        - "bgp log-neighbor-changes"
        - "neighbor 192.168.12.2 remote-as 65002"
        - "neighbor 192.168.12.2 update-source Loopback0"
        - "network 192.168.13.0 mask 255.255.255.0"

    - name: "Configure BGP on iosvl2-01"
      ios_command:
        provider:
          host: "{{ gns3_url }}"
          username: "cisco"
          password: "cisco"
          authorize: yes
          auth_pass: "cisco"
        commands:
        - "router bgp 65002"
        - "bgp log-neighbor-changes"
        - "neighbor 192.168.12.1 remote-as 65001"
        - "neighbor 192.168.12.1 update-source Loopback0"
        - "network 192.168.12.0 mask 255.255.255.0"

    - name: "Configure BGP on iosvl3-02"
      ios_command:
        provider:
          host: "{{ gns3_url }}"
          username: "cisco"
          password: "cisco"
          authorize: yes
          auth_pass: "cisco"
        commands:
        - "router bgp 65003"
        - "bgp log-neighbor-changes"
        - "neighbor 192.168.23.2 remote-as 65004"
        - "neighbor 192.168.23.2 update-source Loopback0"
        - "network 192.168.33.0 mask 255.255.255.0"

    - name: "Configure BGP on iosvl2-02"
      ios_command:
        provider:
          host: "{{ gns3_url }}"
          username: "cisco"
          password: "cisco"
          authorize: yes
          auth_pass: "cisco"
        commands:
        - "router bgp 65004"
        - "bgp log-neighbor-changes"
        - "neighbor 192.168.23.1 remote-as 65003"
        - "neighbor 192.168.23.1 update-source Loopback0"
        - "network 192.168.23.0 mask 255.255.255.0"

    - name: "Configure BGP on iosvl3-03"
      ios_command:
        provider:
          host: "{{ gns3_url }}"
          username: "cisco"
          password: "cisco"
          authorize: yes
          auth_pass: "cisco"
        commands:
        - "router bgp 65005"
        - "bgp log-neighbor-changes"
        - "neighbor 192.168.34.2 remote-as 65006"
        - "neighbor 192.168.34.2 update-source Loopback0"
        - "network 192.168.35.0 mask 255.255.255.0"

    - name: "Configure BGP on iosvl2-03"
      ios_command:
        provider:
        host: "{{ gns3_url }}"
        username: "cisco"
        password: "cisco"
        authorize: yes
        auth_pass: "cisco"



#https://docs.ansible.com/ansible/latest/collections/arista/eos/eos_bgp_global_module.html
#https://docs.ansible.com/ansible/latest/collections/dellemc/enterprise_sonic/sonic_bgp_module.html
